[project]
name = "CLI-example"
version = "1.0.0"
description = "A simple CLI using the click library"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "click",
  "cowsay"
]

[tool.setuptools]
packages = ["mycli"]

[project.scripts]
mycli = "mycli.main:cli"
